config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :grandmoms do
    resources :bookings, only: [:show, :new, :create, :destroy]
  end
  resources :bookings, only: [:index]

  patch 'accept/:id', to: 'bookings#accept', as: 'accept'
  patch 'decline/:id', to: 'bookings#decline', as: 'decline'

  resources :users, only: [:show, :edit, :update, :destroy]
  patch '/userphoto/:id', to: 'users#remove_photo', as: 'user_photo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grandmom

  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/grandmom.rb
class Grandmom < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :owner, class_name: "User", foreign_key: 'user_id'
  has_many :users, through: :bookings, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :address, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :user_id, presence: true

  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  scope :childcare, -> { where(:childcare => true) }
  scope :storytelling, -> { where(:storytelling => true) }
  scope :goforawalk, -> { where(:goforawalk => true) }
  scope :cooking, -> { where(:cooking => true) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :rented_grandmoms, through: :bookings, source: 'user'
  has_many :owned_grandmoms, :class_name => 'Grandmom', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  before_action :set_grandmom, only: [:show, :destroy, :new, :create]
  before_action :authorize_booking, only: [:show]

  def index
    @user = current_user
    @bookings = policy_scope(Booking)
    # @bookings = Booking.all
  end

  def show

  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user_id = current_user.id
    @booking.grandmom_id = params[:grandmom_id]
    if @booking.save
      redirect_to grandmom_booking_path(@grandmom, @booking)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

# not CRUD methods
  def accept
    @booking = Booking.find(params[:id])
    @booking.status = 'Accepted'
    @booking.save
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = 'Declined'
    @booking.save
    redirect_to bookings_path
  end

private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :grandmom_id, :user_id)
  end

  def set_grandmom
    # raise
    @grandmom = Grandmom.find(params[:grandmom_id])
    # raise
  end

  def authorize_booking
    authorize @booking
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/grandmoms_controller.rb
class GrandmomsController < ApplicationController
  before_action :set_grandmom, only: [:show, :edit, :update, :destroy]
  before_action :authorize_grandmom, only: [:show, :edit, :update, :destroy]

    #has_scope :childcare, :type => :boolean
    #has_scope :cooking, :type => :boolean
    #has_scope :goforawalk, :type => :boolean
    #has_scope :storytelling, :type => :boolean

  def index
    @grandmoms = Grandmom.where.not(latitude: nil, longitude: nil)
    @markers = @grandmoms.map do |g|
      {
        lat: g.latitude,
        lng: g.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
    @grandmoms = policy_scope(Grandmom)
    @grandmoms = @grandmoms.where(childcare: params[:childcare]) if params[:childcare].present?
    @grandmoms = @grandmoms.where(cooking: params[:cooking]) if params[:cooking].present?
    @grandmoms = @grandmoms.where(goforawalk: params[:goforawalk]) if params[:goforawalk].present?
    @grandmoms = @grandmoms.where(storytelling: params[:storytelling]) if params[:storytelling].present?
    # filtering_params(params).each do |key, value|
    # @grandmoms = @grandmoms.where(params == true)

  end

  def show
    @booking = Booking.new
    authorize @grandmom
  end

  def new
    @grandmom = Grandmom.new
    authorize @grandmom
  end

  def create
    @grandmom = Grandmom.new(grandmom_params)
    authorize @grandmom
    @grandmom.owner = current_user
    if @grandmom.save
      redirect_to grandmom_path(@grandmom)
    else
      render :new
    end
  end

  def edit
    authorize @grandmom
  end

  def update
    authorize @grandmom
    @grandmom.update(grandmom_params)
    redirect_to grandmom_path(@grandmom)
  end

  def destroy
    authorize @grandmom
    @grandmom.destroy
    redirect_to grandmoms_path
  end

  private

  def grandmom_params
    params[:price] = params[:price].to_i
    params.require(:grandmom).permit(:first_name, :last_name, :description, :address, :price, :cooking, :childcare, :storytelling, :goforawalk, :photo, :latitude, :longitude)
  end

  def set_grandmom
    @grandmom = Grandmom.find(params[:id])
  end

  def authorize_grandmom
    authorize @grandmom
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :remove_photo]
  before_action :authorize_user, only: [:show, :remove_photo]

  def show
    @grandmoms_owned = Grandmom.where(user_id: current_user)
    @bookings = Booking.where(user_id: current_user)
    @user = current_user
  end

  def update
    authorize @user
    @user = current_user
    @user.update(current_user_params)
    redirect_to user_path(@user)
  end

  def destroy
  end

  def remove_photo
    @user = current_user
    @user.remove_photo!
    @user.save
    redirect_to user_path(@user)
  end

private

  def current_user_params
    params.require(:user).permit(:email, :photo)
  end

  def authorize_user
    authorize @user
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/views/bookings/index.html.erb
<div class="complete-page">
  <div class="status-margin">
    <% @bookings.each do |booking| %>
      <% if booking.user == current_user %>
        <div class="message">
            <% grammy = Grandmom.find(booking.grandmom_id) %>
            <div>
              <%= image_tag grammy.photo.url(:bright_face), class:'profile-image-small-square' %>
            </div>
            <div class="message-body">
              <h3><%= grammy.first_name %></h3>
              <p>Start: <%= booking.start_time %></p>
              <p>End: <%= booking.end_time %></p>
            </div>
            <div class="message-status">
              <% if booking.status == 'pending' %>
                <p class="status pending"><%= booking.status %></p>
              <% elsif booking.status == 'accepted' %>
                <p class="status accepted"><%= booking.status %></p>
              <% elsif booking.status == 'declined' %>
                <p class="status declined"><%= booking.status %></p>
              <p class="price"><%= booking.price %></p>
              <% end %>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<h1>Create a new booking for <%= @grandmom.first_name %> <%= @grandmom.last_name %>!</h1>

<%= simple_form_for [@grandmom, @booking] do |f| %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', grandmoms_path %> <br>

app/views/bookings/show.html.erb
<div class="show-main flexbox">
  <div class="photo">
    <% grammy = Grandmom.find(@booking.grandmom_id) %>
    <%= image_tag @grandmom.photo.url(:bright_face), class:'profile-image-big-square' %>
  </div>
  <div class="details">
    <h1> Booking Number #<%=  @booking.id %> </h1>
    <% grammy = Grandmom.find(@booking.grandmom_id) %>
    <table style="width:50%">
      <tr>
        <td><strong>Grandma:</strong></td>
        <td><%= grammy.first_name %> <%= grammy.last_name %></td>
      </tr>
      <tr>
        <td><strong>User:</strong></td>
        <td><%= User.find(@booking.user_id).email %></td>
      </tr>
      <tr>
        <td><strong>From:</strong></td>
        <td><%= @booking.start_time %></td>
      </tr>
      <tr>
        <td><strong>Until:</strong></td>
        <td><%= @booking.end_time %></td>
      </tr>
      <tr>
        <td><strong>Status:</strong></td>
        <td><strong><%= @booking.status %></strong></td>
      </tr>
    </table>
    <br>
    <%= link_to 'Delete', grandmom_booking_path(grammy, @booking), method: 'delete', class: "btn btn" %>
    <%= link_to 'Back', root_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/grandmoms/edit.html.erb
<h1>Grandmoms#update</h1>
<p>Edit a existing Grandmom</p>

<%= simple_form_for @grandmom, method:'patch' do |g| %>
  <%= g.input :first_name %>
  <%= g.input :last_name %>
  <%= g.input :photo %>
  <%= g.input :photo_cache, as: :hidden %>
  <%= g.input :address %>
  <%= g.input :description, as: :text %>
  <%= g.input :price %>
  <%= g.input :cooking, as: :radio_buttons %>
  <%= g.input :childcare, as: :radio_buttons %>
  <%= g.input :storytelling, as: :radio_buttons %>
  <%= g.input :goforawalk, as: :radio_buttons %>
  <%= g.button :submit %>
<% end %>

app/views/grandmoms/index.html.erb
<h3>Find the right Grandma' for every purpose</h3>

<div class="icons-container">
  <%= link_to "All", grandmoms_path, class: "btn btn-primary" %>
  <%= link_to "Childcare", grandmoms_path({childcare: true}), class: "btn btn-primary" %>
  <%= link_to "Storytelling", grandmoms_path({storytelling: true}), class: "btn btn-primary" %>
  <%= link_to "Go for a walk", grandmoms_path({goforawalk: true}), class: "btn btn-primary"  %>
  <%= link_to "Cooking & Baking", grandmoms_path({cooking: true}), class: "btn btn-primary" %>
</div>

<div class="grandmom-container">
  <div class="container">
    <div class="row">
      <% @grandmoms.each do |grandmom| %>
        <div class="col-md-4">
          <div class="card">
            <% unless grandmom.photo.blank? %>
              <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path grandmom.photo, height: 300, width: 400, crop: :fill %>')">
                <h4 class="card-grandmom-name"><%= link_to grandmom.first_name, grandmom_path(grandmom)%></h4>
              </div>
              <% else %>
              <div class="card-body" style="background-image: url('https://source.unsplash.com/random')">
                <h5 class="card-grandmom-name"><%= link_to grandmom.first_name, grandmom_path(grandmom)%></h5>
              </div>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/grandmoms/new.html.erb
<div class="complete-page">
  <%= simple_form_for(@grandmom, method:'post') do |g| %>
    <div class="main-container">

      <div class="container-left">
        <div class="image-container">
          <%= cl_image_tag 'http://res.cloudinary.com/twentythree/image/upload/v1527256813/profile_placeholder.jpg', class:'profile-image-big-square' %>
          <%= g.input :photo %>
          <%= g.input :photo_cache, as: :hidden %>
        </div>

        <div class="skills-box">
          <div class="row-container">
            <div class="flexbox-row">
              <h3 class="box-header">Skills</h3>
            </div>
            <div class="flexbox-row">
              <div>
                <%= g.input_field :childcare, as: :boolean, boolean_style: :inline %> Childcare
              </div>
              <div><i class="fas fa-child fa"></i></div>
            </div>
            <div class="flexbox-row">
              <div>
                <%= g.input_field :storytelling, as: :boolean, boolean_style: :inline %> Storytelling
              </div>
              <div><i class="fas fa-book-open fa"></i></div>
            </div>
            <div class="flexbox-row">
              <div><%= g.input_field :goforawalk, as: :boolean, boolean_style: :inline %> Going for a Walk</div>
              <div><i class="fas fa-walking fa"></i></div>
            </div>
            <div class="flexbox-row">
              <div><%= g.input_field :cooking, as: :boolean, boolean_style: :inline %> Cooking</div>
              <div><i class="fas fa-utensils fa"></i></div>
            </div>
          </div>
        </div>

      </div>

      <div class="container-center">
        <div class="headline">
          <h3>Add a new Grandmom!</h3>
          <%= g.input :first_name %> <%= g.input :last_name %>
          <%= g.input :address, input_html: {id: 'grandmom_address' } %>
          <%= g.input :description, as: :text %>
          <%= g.input :price %>
          <div><%= g.button :submit, class:'button-box-new' %></div>
        </div>
      </div>

      <div class="container-right">

      </div>
    </div>
  <% end %>
</div>

app/views/grandmoms/show.html.erb
<div class="complete-page">

  <div class="main-container">

    <div class="container-left">
      <div >
        <% if @grandmom.photo.present? %>
          <%= image_tag @grandmom.photo.url(:bright_face), class:'profile-image-big-square' %>
        <% else %>
          <%= image_tag 'profile_placeholder.jpeg', class:'profile-image-big-square' %>
        <% end %>
      </div>

      <div>
        <div class="row-container verified-info">
          <div class="flexbox-row">
            <h3 class="box-header">Verified info</h3>
          </div>
          <div class="flexbox-row">
            <div><p>Government ID</p></div>
            <div><i class="far fa-check-circle"></i></div>
          </div>
          <div class="flexbox-row">
            <div><p>Selfie</p></div>
            <div><i class="far fa-check-circle"></i></div>
          </div>
          <div class="flexbox-row">
            <div><p>Email address</p></div>
            <div><i class="far fa-check-circle"></i></div>
          </div>
          <div class="flexbox-row">
            <div><p>Phone number</p></div>
            <div><i class="far fa-check-circle"></i></div>
          </div>
          <div class="flexbox-row"><p>Learn more »</p></div>
        </div>
      </div>
    </div>

    <div class="container-center">
      <div class="headline">
        <h2><%= @grandmom.first_name %> <%= @grandmom.last_name %></h2>
        <h5><%= @grandmom.address %></h5>
        <br>
        <p><%= @grandmom.description %></p>
        <br>
        <p><i class="fas fa-euro-sign"></i> <%= @grandmom.price %></p>
      </div>

      <div class="skills-box">
        <div class="row-container">
          <div class="flexbox-row">
            <h3 class="box-header">Skills</h3>
          </div>
          <div class="flexbox-row">
            <div><p>Childcare</p></div>
            <div><% if @grandmom.childcare == true %><i class="fas fa-child fa green" ></i><% else %><i class="far fa-times-circle red"></i><% end %></div>
          </div>
          <div class="flexbox-row">
            <div><p>Storytelling</p></div>
            <div><% if @grandmom.storytelling == true %><i class="fas fa-book-open fa green" ></i><% else %><i class="far fa-times-circle red"></i><% end %></div>
          </div>
          <div class="flexbox-row">
            <div><p>Going for a Walk</p></div>
            <div><% if @grandmom.goforawalk == true %><i class="fas fa-walking fa green" ></i><% else %><i class="far fa-times-circle red"></i><% end %></div>
          </div>
          <div class="flexbox-row">
            <div><p>Cooking</p></div>
            <div><% if @grandmom.childcare == true %><i class="fas fa-utensils green" ></i><% else %><i class="far fa-times-circle red"></i><% end %></div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-right">
      <div class="button-box">
        <%= link_to "Home", grandmoms_path, class: "btn btn-primary flex-element" %>
        <% if policy(@grandmom).update? %> <%= link_to "Edit", edit_grandmom_path(@grandmom), class: "btn btn-primary flex-element" %> <% end %>
        <% if policy(@grandmom).destroy? %> <%= link_to "Delete", grandmom_path, method:'delete', class: "btn btn-primary flex-element" %> <% end %>
        <button type="button" class="btn btn-primary flex-element" data-toggle="modal" data-target="#myModal">
        Book
        </button>
      </div>

      <!-- Button to Open the Modal -->


      <!-- The Modal -->
      <div class="modal" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Select your dates</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">

              <div class="container">
                <%= simple_form_for [@grandmom, @booking] do |f| %>
                  <div class='col-md-3'>
                    <div class="form-group">
                      <div class='input-group date' id='datetimepicker6'>
                        <input type='text' class="form-control" name="booking[start_time]" />
                        <%# f.input :start_time, class: 'form-control' %>
                        <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                      </div>
                    </div>
                  </div>

                  <div class='col-md-3 rightside'>
                    <div class="form-group">
                      <div class='input-group date' id='datetimepicker7'>
                        <input type='text' class="form-control" name="booking[end_time]"/>
                        <%# f.input :end_time, class: 'form-control' %>
                        <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                      </div>
                    </div>
                  <%= f.submit 'Book', :class => 'book_button'  %>
                  </div>
                <% end %>
              </div>
              <script type="text/javascript">


              </script>

            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <title>GrandmAirBnB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'components/navbar' %>

    <%= yield %>

    <%#= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main-page-home">
 <div class="body-home">
  <div class="headline-home">
    <h1> Book a Grandmom </h1>
  </div>
  <div class="subtitle">
    <h3> Find a Grandmom in your region <br> and have an awesome time! </h3>
  </div>
  <div>
    <div class="search-home">
        <%= form_tag grandmoms_path, method: :get, class: 'searchbox-home' do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: 'grandmom_address',
            placeholder: "Type in your address"
          %>
        <%= submit_tag 'Search', :class => 'searchbutton' %>
        <% end %>
    </div>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="flexbox-user">

  <div class="main-container-user">
    <h1>User Profile</h1>
    <div class="top-user">
      <div>
        <% if @current_user.photo.present? %>
          <%= cl_image_tag @current_user.photo, height: 150, width: 200, crop: :fill %> <br>
          <%= link_to 'Delete', user_photo_path(current_user), method: :patch%>
        <% else %>
          <%= simple_form_for(@current_user) do |f| %>
            <!-- [...] -->
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.button :submit, value: 'Upload photo' %>
          <% end %>
        <% end %>
      </div>
      <div>
        <h4>Email:</h4>
        <p><%= current_user.email %></p>
      </div>
    </div>
  </div>

  <div class=container-your-grandmoms>
    <h1>Your Grandmoms</h1>
    <div class="row">
      <% @grandmoms_owned.each do |grandmom| %>
      <div class="col-md-4">
        <div class="card-own-gm">
          <div class="body-own-gm">
            <% unless grandmom.photo.blank? %>
              <div class="card-own-gm-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
            url('<%= cl_image_path grandmom.photo, height: 300, width: 400, crop: :fill %>')">
              <h4 class="gm-design"><%= link_to grandmom.first_name, grandmom_path(grandmom)%></h4>
              </div>
            <% else %>
              <div class="card-own-gm" style="background-image: url('https://source.unsplash.com/random')">
              <h4><%= link_to grandmom.first_name, grandmom_path(grandmom)%></h4>
              </div>
            <% end %>
         </div>
         <div class="footer-own-gm">
           <div class="edit">
             <%= link_to edit_grandmom_path(grandmom) do %>
              <i class="fas fa-edit"></i>
             <% end %>
           </div>
           <div class="delete">
             <%= link_to grandmom_path(grandmom), method: :delete, data: {confirm:"Are you sure?"} do %>
               <i class="fas fa-trash"></i>
             <% end %>
           </div>
         </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>